# Generated by Django 5.2.9 on 2026-02-24 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_activation_restart_and_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="import_warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="project",
            name="scm_type",
            field=models.TextField(
                choices=[("git", "Git"), ("archive", "Archive")], default="git"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "rrule",
                    models.TextField(
                        help_text="RFC 5545 RRULE string for schedule recurrence"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "last_run",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_schedule",
                "ordering": ["id"],
            },
        ),
    ]
